### ISSUE TITLE
Komadu-1.0 Build Fail: GraphGenerator.java > unrecognized symbol QNAME_SXD_STRING

### ISSUE THREAD

**Issue by sid-thakur** [Data-to-Insight-Center/komadu#3]
Hi @isurues 
I am trying to compile komadu-1.0 on Fedora 20/x86_64 bit machine. I followed the build steps given in the repository's documentation and am experiencing compilation error when building from source.

Note: I had to make change to version of org.openprovenance prior to compilation of the code. I edited komadu-1.0/pom.xml and changed following line 
```
<prov.version>0.4.0</prov.version>
```
to
```
<prov.version>0.6.1</prov.version>
```
as specified by the latest version of the repository on maven central page: http://search.maven.org/#search|ga|1|prov-model 

The error below seems to be limited to the graph library in `komadu-1.0/service-core/src/main/java/edu/indiana/d2i/komadu/query/graph` folder
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/sthakur/Documents/las-instr/provenance/komadu/komadu-1.0/service-core/src/main/java/edu/indiana/d2i/komadu/query/graph/GraphGenerator.java:[248,36] cannot find symbol
  symbol:   variable QNAME_XSD_STRING
  location: class org.openprovenance.prov.model.Name
[ERROR] /home/sthakur/Documents/las-instr/provenance/komadu/komadu-1.0/service-core/src/main/java/edu/indiana/d2i/komadu/query/graph/GraphGenerator.java:[318,96] cannot find symbol
  symbol:   variable QNAME_XSD_STRING
  location: class org.openprovenance.prov.model.Name
:
```

Please advise on how to fix the above error and thanks in advance!
Sid Thakur

**Comment by isurues** [comment]
Hi Sid,

Thank you for your interest in Komadu. We haven't upgraded the Komadu code
to be compatible with ProvToolbox 0.6.1. Komadu 1.0 depends
on ProvToolbox 0.4.0. Therefore, to build Komadu code, you'll have to
download ProvToolbox 0.4.0 code from [1] and build it first and then build
Komadu 1.0.

More information can be found in [2]. Just let me know if you'll have
further issues.

Thanks,
Isuru

[1] https://github.com/lucmoreau/ProvToolbox/releases/tag/ProvToolbox-0.4.0
[2] http://d2i.indiana.edu/sites/default/files/komaduuserguide.pdf

**Comment by sid-thakur** [comment]
Hi Isuru,
Thanks for the update. I will give that a shot. 

A related question - once I compile ProvToolbox 0.4.0, how do I make sure `komadu-1.0/pom.xml` uses my local, compiled version (0.4.0) and not the version 0.6.1 on maven.central? 
I see references to ` <artifactId>prov-model</artifactId>` and ` <artifactId>prov-xml</artifactId>` in `komadu-1.0/pom.xml` but nowhere I can point maven to use local 0.4.0 version.
Thanks!

**Comment by isurues** [comment]
Hi Sid,

After building ProvToolbox 0.4.0 locally, you have to revert your local
changes to Koamdu root pom.xml. It should point to 0.4.0 as shown below.

<prov.version>0.4.0</prov.version>

Then the build won't try to download ProvToolbox libraries from maven
central as the required version is already there in your local maven
repository.

Thanks,
Isuru

**Comment by sid-thakur** [comment]
Hi,
I was able to successfully build komadu-1.0 after downgrading prov to ProvToolbox-0.4.0. 

Just an observation: when I went to the individual directories in ProvToolbox to build prov-model and prov-xml, former compiled fine but prov-xml aborted with errors. I tried to compile all modules in parent, ProvToolbox-0.4.0 directory and all modules except prov-sql compiled fine. I gather prov-sql is not needed for komadu, so that shouldn't be an issue for now.

Now onto trying to run komadu using RabbitMQ. 
Thanks for your help.
Sid

**Comment by isurues** [comment]
Hi Sid,

Great to hear that you were able to build it successfully. Yeah, I think I
also had that issue while building ProvToolbox. Anyway, we'll be updating
the ProvToolbox version in our next release.

Let me know if you run into further issues.

Thanks,
Isuru

**Comment by sid-thakur** [comment]
Hi Isuru,

I had trouble building komadu messaging client but managed to do so after a minor change to build configuration: you might want to update the target `komadu-service-1.0.jar` in `komadu-1.0/client-core-messaging/build.xml`

I was trying to execute following steps to run komadu as standalone server
```
#Build Komadu Messaging Client

cd {komadu_checkout_path}/client-core-messaging
ant
```

Ant failed with following message: 
```
Buildfile: /home/sthakur/Documents/las-instr/provenance/komadu/komadu-1.0/client-core-messaging/build.xml

init:
    [mkdir] Created dir: /home/sthakur/.../komadu-1.0/client-core-messaging/build
    [mkdir] Created dir: /home/sthakur/.../komadu-1.0/client-core-messaging/build/classes
    [mkdir] Created dir: /home/sthakur/.../komadu-1.0/client-core-messaging/build/lib

BUILD FAILED
/home/sthakur/.../komadu-1.0/client-core-messaging/build.xml:26: Warning: Could not find file /home/sthakur/.../komadu-1.0/service-core/target/komadu-service-core-1.0.jar to copy.
```
I checked and found target jar with slightly different version in its file name:
```
[sthakur@localhost komadu-1.0]$ ls service-core/target/
classes  dependency  generated-code  generated-sources  komadu-service-core-1.0.0.jar  maven-archiver  maven-status
```
I was able to compile successfully by changing the target to `komadu-service-core-1.0.0.jar` in build file `komadu-1.0/client-core-messaging/build.xml` and re-running ant.

**Comment by sid-thakur** [comment]
I am able to run the examples in the folder `..../client-core-messaging/samples`
